### ISSUE TITLE
ModuleNotFoundError: No module named 'httpx'

### ISSUE THREAD

**Issue by rudolphos** [nxvvvv/warp-plus#11]
After running can't install httpx
```
Successfully installed anyio certifi exceptiongroup h11 httpcore httpx idna sniffio typing-extensions
Traceback (most recent call last):
  File "/home/runner/warp-plus-2/main.py", line 11, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/warp-plus-2/main.py", line 15, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
```

**Comment by nxvvvv** [comment]
Fixed it with the latest [update](https://github.com/nxvvvv/warp-plus/commit/d3e5aab3a06882a269e751e58a8a7071f9477f19) :)

Just click run again and it will run: 
![image](https://github.com/nxvvvv/warp-plus/assets/34748927/e166ec91-0f3c-44d0-8f06-ef42d71da7e2)
